### ISSUE TITLE
Page Not found Issue after successful deployment on netlify.

### ISSUE THREAD

**Issue by mhaseeb37** [netlify/hydrogen-platform#137]
I used hydrogen/plugin also updated the vite.config.js in the remix template of hydrogen. Added netlify.toml file. 
After successful deployment the page not found error is coming. 
Any Solution?

**Comment by ascorbic** [comment]
Hi. We're in the process of updating the template to support Remix 2, which should be ready later this week.

**Comment by ascorbic** [comment]
Please see https://github.com/netlify/hydrogen-template
