### ISSUE TITLE
Provide cache object to Hydrogen

### ISSUE THREAD

**Issue by frandiox** [netlify/hydrogen-platform#36]
I'm not very familiar with Deno and its platform-as-a-service features but, if possible, it would be great if we can provide a `cache` in the handler like we do in our [Oxygen handler](https://github.com/Shopify/hydrogen/blob/3c70f662ae60e8ac9e4dfccd3ed59eef99221b11/packages/hydrogen/src/platforms/worker.ts#L32).
We use this to cache subrequests and full page SSR.

**Comment by ascorbic** [comment]
This is currently waiting on support in Deno Deploy. This [as planned](https://deno.com/deploy/docs/runtime-api#future-support), but we're not sure when it will be added. As soon as it is then we'll add framework support. @AaronO might know more about timelines. I wonder if there would be any value in an in-memory cache polyfill in the meantime, so it's at least cached per-isolate.

**Comment by frandiox** [comment]
We have an [experimental in-memory implementation](https://github.com/Shopify/hydrogen/blob/v1.x-2022-07/packages/hydrogen/src/framework/cache/in-memory.ts) that I think can be imported with `import {InMemoryCache} from '@shopify/hydrogen/framework/cache/in-memory';`. Perhaps that's good enough for now 🤔

**Comment by AaronO** [comment]
> This is currently waiting on support in Deno Deploy. This [is planned](https://deno.com/deploy/docs/runtime-api#future-support), but we're not sure when it will be added. As soon as it is then we'll add framework support. I know Remix is waiting for this too. @AaronO might know more about timelines. I wonder if there would be any value in an in-memory cache polyfill in the meantime, so it's at least cached per-isolate.

I left Deno earlier this week, so can't comment on it

**Comment by ascorbic** [comment]
Ah, my apologies @AaronO. That's certainly worth a try, @frandiox

**Comment by MarcL** [comment]
Looks like the PR for this issue has been merged so closing it.

**Comment by MarcL** [comment]
Ah ok - thanks @ascorbic. Reopening. 👍🏻
