### ISSUE TITLE
Site never loads when use Oxygen globally outside of some function

### ISSUE THREAD

**Issue by VitaliyR** [netlify/hydrogen-platform#54]
Hey!

When I'm using `Oxygen` globally outside of some function, site will never load and eventually connection truncated with 502 status code.

Example:

```
// useContentfulQuery.ts

// WRONG! Don't use Oxygen on the root level, it works in preview mode
// but fails in the Netlify Edge
const SPACE_ID = Oxygen.env.CONTENTFUL_SPACE_ID;
const ACCESS_TOKEN = Oxygen.env.CONTENTFUL_PREVIEW_TOKEN;

export const useContentfulQuery = () => {
  // CORRECT
  // Use Oxygen within some function
  const SPACE_ID = Oxygen.env.CONTENTFUL_SPACE_ID;
  const ACCESS_TOKEN = Oxygen.env.CONTENTFUL_PREVIEW_TOKEN;
};
```

If I'm using `Oxygen` where "wrong" written - site never loads and neither any logs entries on Netlify's Edge console page.

If I move these lines into `useContentfulQuery` - site loads & works fine.

**Comment by ascorbic** [comment]
Thanks! I think I know what's happening here. The workaround for now would be to use `Deno.env.get('CONTENTFUL_SPACE_ID')` instead.

**Comment by ascorbic** [comment]
This fix, for anyone who can take this, is to move these lines up to the top level, outside the handler:
https://github.com/netlify/hydrogen-platform/blob/main/src/handler.ts#L22-L24

**Comment by VitaliyR** [comment]
@ascorbic thanks! Added a PR for a reference with proposed fix. Also verified with my site (see PR)
