### ISSUE TITLE
Hydrogen v17 not supported?

### ISSUE THREAD

**Issue by spidgorny** [netlify/hydrogen-platform#7]
I've tested hydrogen v13 (from the sample repository) and it is working fine.
I've tried deploying hydrogen v17 (created new repo).

Build was successful, but it has issues here:

https://master--curious-cupcake-165d0d.netlify.app/

index.html loaded fine, but most JS files are 404 or 503.

![image](https://user-images.githubusercontent.com/1579235/165638813-1b7b18b9-3129-47b1-927a-01548de0d193.png)

Any recommendations to fix that?
I suppose I don't have access to the log files, so I don't know what happens.

Thanks.

**Comment by robhyrk** [comment]
I'm having a similar issue here: https://tourmaline-begonia-40337a.netlify.app/

I followed the config settings for Netlify here: https://github.com/netlify/hydrogen-platform#installation

Getting either 404 or 502 errors which leads me to believe there is an issue with how the files are being bundled. Below is my package.json

`{
  "name": "high-grade",
  "description": "This the default template for Hydrogen",
  "version": "0.0.0",
  "license": "MIT",
  "private": true,
  "scripts": {
    "dev": "shopify hydrogen dev",
    "lint": "npm-run-all lint:*",
    "lint:js": "eslint --no-error-on-unmatched-pattern --ext .js,.ts,.jsx,.tsx src",
    "lint:css": "stylelint ./src/**/*.{css,sass,scss}",
    "build": "npm run build:client && npm run build:ssr",
    "build:client": "vite build --outDir dist/client --manifest",
    "build:server": "vite build --outDir dist/server --ssr @shopify/hydrogen/platforms/node",
    "build:worker": "cross-env WORKER=true vite build --outDir dist/worker --ssr @shopify/hydrogen/platforms/worker",
    "build:ssr": "cross-env WORKER=true vite build --ssr @netlify/hydrogen-platform/handler",
    "serve": "node --enable-source-maps dist/server",
    "test": "WATCH=true vitest",
    "test:ci": "yarn build && vitest run",
    "preview": "shopify hydrogen preview"
  },
  "prettier": "@shopify/prettier-config",
  "devDependencies": {
    "@netlify/hydrogen-platform": "^0.0.2",
    "@shopify/cli": "1.0.9",
    "@shopify/cli-hydrogen": "2.0.0",
    "@shopify/prettier-config": "^1.1.2",
    "@shopify/stylelint-plugin": "^10.0.1",
    "@tailwindcss/typography": "^0.5.2",
    "autoprefixer": "^10.4.2",
    "cross-env": "^7.0.3",
    "eslint": "^7.31.0",
    "eslint-plugin-hydrogen": "^0.12.1",
    "npm-run-all": "^4.1.5",
    "playwright": "^1.19.2",
    "postcss": "^8.4.5",
    "prettier": "^2.3.2",
    "stylelint": "^13.13.0",
    "tailwindcss": "^3.0.0",
    "vite": "^2.9.0",
    "vitest": "^0.5.9"
  },
  "dependencies": {
    "@headlessui/react": "^1.5.0",
    "@shopify/hydrogen": "^0.17.1",
    "body-parser": "^1.19.1",
    "compression": "^1.7.4",
    "graphql-tag": "^2.12.4",
    "react": "0.0.0-experimental-2bf7c02f0-20220314",
    "react-dom": "0.0.0-experimental-2bf7c02f0-20220314",
    "serve-static": "^1.14.1"
  }
}
`

**Comment by nickytonline** [comment]
Thanks for reporting @robhyrk! @orinokai is working on a fix for this.

**Comment by orinokai** [comment]
This issue should be resolved with the next patch release of Hydrogen. Relevant issue is here: https://github.com/Shopify/hydrogen/pull/1211

**Comment by nickytonline** [comment]
@idbakkasse, can you provide more information on the issue you're having and if possible a minimal reproduction? Sharing a repository where you exhibit the issue would be best. Also, did you see https://github.com/Shopify/hydrogen/pull/1211?

**Comment by ascorbic** [comment]
Fixed in 1.0.0
