### ISSUE TITLE
Netlify redirects are not working when using the plugin

### ISSUE THREAD

**Issue by patrick-schneider-latori** [netlify/hydrogen-platform#70]
When I include the plugin inside of the `vite.config.js` file, no redirects are working anymore. Unfortunately it does not matter if I place a `_redirects` file in the public folder or place the redirects inside of the `netlify.toml` configuration file – the edge handler completely ignores those redirects.

**Comment by ascorbic** [comment]
Hi Patrick. This is because the site is served from edge funcitons, which run before redirects. Unfortunately the only workaround for this is to implement the redirects in Hydrogen, for example [like this](https://shopify.dev/custom-storefronts/hydrogen/framework/routes#examples)

**Comment by sarahetter** [comment]
@patrick-schneider-latori Can you confirm that @ascorbic 's solution fixed your issue?
